# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBookRecommendationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_index', models.FloatField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_movies_info', to='books.Book')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_books_info', to='movies.Movie')),
            ],
            options={
                'ordering': ['-recommendation_index'],
            },
        ),
        migrations.CreateModel(
            name='MovieBookSimilarRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_index', models.FloatField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_movies_info', to='books.Book')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_books_info', to='movies.Movie')),
            ],
            options={
                'ordering': ['-similarity_index'],
            },
        ),
    ]
