# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_productioncompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(blank=True, max_length=3, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
