# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_spokenlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
